export const metadata = {
  title: "Home",
  description: "Generated by Next.js",
};

import { Button } from "antd";
import axios from "axios";
import Link from "next/link";
import HeaderPage from "./Component/HeaderPage";

import FooterContainer from "./Component/FooterContainer";
import MoreRandomItem from "./Component/MoreRandomItem";

const MainPage = async () => {
  let ProductDetails = [];
  try {
    const response = await axios.get(
      "http://localhost:8000/products/randomProducts"
    );

    ProductDetails = response.data.productDetails;
  } catch (e) {
    return <>something went wrong</>;
  }

  return (
    <>
      <HeaderPage />

      <div className="flex flex-col items-center gap-5 w-[100%] p-5 bg-[whitesmoke]">
        <div className="w-[100%]">
          <div className="gridContainer grid gap-5   ">
            {ProductDetails.map((element: any) => (
              <>
                <Link href={`/productDetails/${element._id}`}>
                  <div className="product-container flex flex-col items-center  gap-5  rounded-sm p-5 bg-white  border-[1px] border-[whitesmoke] hover:cursor-pointer">
                    <div className="flex flex-col items-center flex-wrap gap-5">
                      <div className="flex flex-col items-center gap-1">
                        <div
                          style={{
                            backgroundImage: `url(${element.ProductImage})`,
                          }}
                          className="productImage h-[100px] w-[100px]"
                        ></div>{" "}
                        <p>{element.ProductName}</p>
                        <p className="text-red-400">
                          Rs.{element.ProductPrice}
                        </p>
                      </div>
                    </div>
                  </div>
                </Link>
              </>
            ))}
          </div>
        </div>

        <div className="w-[100%]">
          <MoreRandomItem homeProductDetails={ProductDetails} />
        </div>
      </div>
      <FooterContainer />
    </>
  );
};
export default MainPage;
