export const metadata = {
  title: "serached",
  description: "Generated by Next.js",
};

import HeaderPage from "@/app/Component/HeaderPage";
import { Button } from "antd";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/navigation";

const page = async ({ params }: any) => {
  const { searchItem } = params;

  let ProductDetails = [];
  try {
    const response = await axios.get(
      `http://localhost:8000/products/searchProducts?search=${searchItem}`
    );

    ProductDetails = response.data.data;

    console.log(response.data.data.length);
    if (response.data.data.length === 0) {
      return (
        <>
          <div className="h-[100%] w-[100%]">
            <HeaderPage searchedValue={searchItem} />
            <div className="flex justify-center p-10">
              <p className="text-gray-500 font-bold text-4xl">
                No products found
              </p>
            </div>
          </div>
        </>
      );
    }
    console.log(ProductDetails);
  } catch (e) {
    return <>something went wrong</>;
  }
  return (
    <>
      <div className="    bg-white ">
        <HeaderPage searchedValue={searchItem} />
        <div className="w-[100%]">
          <div className="gridContainer grid gap-5 p-5 ">
            {ProductDetails.map((element: any) => (
              <>
                <div className="product-container flex flex-col items-center  gap-5  rounded-sm p-5 bg-white box-shadow ">
                  <div className="flex flex-col items-center flex-wrap gap-5">
                    <div className="flex flex-col items-center gap-1">
                      <div
                        style={{
                          backgroundImage: `url(${element.ProductImage})`,
                        }}
                        className="productImage h-[100px] w-[100px]"
                      ></div>{" "}
                      <p>{element.ProductName}</p>
                      <p className="text-red-400">Rs.{element.ProductPrice}</p>
                    </div>
                    <Link href={`/productDetails/${element._id}`}>
                      <Button>Details</Button>
                    </Link>
                  </div>
                </div>
              </>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};
export default page;
